--- # Configuration for loading a dataset and training.

dataset:
  skip_download: true
  image_scale: 224
  annotation_id: 0bfbe00d-00fa-4555-88d1-471b58449f5c
  schema_version: 0.0.1
  symmetric: false

train:
  source_uri: gs://canary-ml-data/tutorials/unity/UR3_single_cube_training.zip
  batch_size: 20
  sample_size: 0
  accumulation_steps: 10
  epochs: 120
  beta_loss: 1

validation:
  source_uri: gs://canary-ml-data/tutorials/unity/UR3_single_cube_validation.zip
  batch_size: 30
  sample_size: 0
  eval_freq: 4

system:
  log_dir_system: /save/single_cube
  data_root: /data
