name: pose_estimation
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - click
  - cudatoolkit
  - cudnn
  - flake8
  - isort
  - jupyter
  - pip
  - pytest
  - pytest-cov
  - pytorch
  - torchvision
  - docopt
  - black
  - pyyaml

  - pip:
      - kfp
      - easydict
      - tensorboardX
