name: pose_estimation
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - click
  - cudatoolkit
  - cudnn
  - jupyter
  - pip
  - pytest
  - pytest-cov
  - docopt

  - pip:
      - kfp
      - black
      - datasetinsights
      - easydict
      - flake8
      - flake8-black
      - isort
      - PyYAML
      - tensorboardX
      - torchvision
